# Generated by Django 5.0.2 on 2024-03-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, default="default_user.jpg", upload_to="users/%Y/%m/%d"
            ),
        ),
    ]
